name: Deploy para Firebase Hosting

on:
  push:
    branches:
      - main  # ou "principal", se o nome da sua branch for esse

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy para Firebase Hosting
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
