name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Sempre que você fizer push na branch main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy no Firebase Hosting
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
